### ISSUE TITLE
Prepare to publish new release 0.1.0 of collection

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.okd#25]
This issue is to track preparation and publishing of 0.1.0 of this collection to Galaxy. It is a community supported release containing only to the OpenShift parts of the community.kubernetes collection that have been extracted.

- [x] Update galaxy.yml, the Makefile, and this README's requirements.yml example with the new version for the collection.
- [x] Update the CHANGELOG (See #24)
- [x] Commit the changes and create a PR with the changes
- [x] Merge that PR
- [x] Tag the version in Git and push to GitHub

**Comment by geerlingguy** [comment]
It lives! Onward towards 0.2 or 1.0 :)
